---
- stat:
    path: "{{solr_home}}/solr_cloud_mode.flag"
  register: solr_cloud_mode

- name: Add ansible_user to sudoers file
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers.d/solr
    owner: root
    mode: 0644

- synchronize:
    src: "{{item.src}}"
    dest: "{{solr_home}}/{{item.dest}}"
    recursive: yes
    delete: yes
  with_items: "{{solr_config_templates_to_sync}}"

- name: Remove ansible_user to sudoers file
  file:
    path: /etc/sudoers.d/solr
    state: absent

- file:
    path: "{{solr_home}}"
    recurse: yes
    owner: solr
    group: solr

- set_fact: server_id="{{ item.id }}"
  with_items: "{{zookeeper_hosts}}"
  when: item.host == inventory_hostname

- name: Create core directory
  file:
    path: "{{solr_home}}/data/{{solr_config_core_name}}_{{server_id}}"
    state: directory
    mode: 0755
    owner: solr
    group: solr

- name: Copy core.properties file
  template:
    src: templates/core.properties_cloud.j2
    dest: "{{solr_home}}/data/{{solr_config_core_name}}_{{server_id}}/core.properties"
    owner: solr
    mode: 0644
  when: solr_cloud_mode.stat.exists

- name: Copy core.properties file
  template:
    src: templates/core.properties_standalone.j2
    dest: "{{solr_home}}/data/{{solr_config_core_name}}_{{server_id}}/core.properties"
    owner: solr
    mode: 0644
  when: not solr_cloud_mode.stat.exists

- name: Create link config for solr core
  file:
    src: "{{solr_home}}/{{solr_config_core_path}}"
    dest: "{{solr_home}}/data/{{solr_config_core_name}}_{{server_id}}/conf"
    owner: solr
    group: solr
    state: link
  when: not solr_cloud_mode.stat.exists

- name: Active core in Zookeeper
  command: bash -c "su - solr -c '{{solr_install_path}}/bin/solr zk upconfig -n {{solr_config_core_name}} -d {{solr_home}}/{{solr_config_core_path}}'"
  when: solr_cloud_mode.stat.exists
