---
- name: Add ansible_user to sudoers file
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers.d/solr
    owner: root
    mode: 0644

- synchronize:
    src: "{{solr_config_templates}}"
    dest: "{{solr_home}}/"
    recursive: yes
    delete: yes

- name: Remove ansible_user to sudoers file
  file:
    path: /etc/sudoers.d/solr
    state: absent

- file:
    path: "{{solr_home}}"
    recurse: yes
    owner: solr
    group: solr
