---

- copy:
    src: "{{solr_config_templates}}"
    dest: "{{solr_home}}/data/"
    owner: solr
    group: solr

- template:
    src: "{{item.src}}"
    dest: "{{solr_home}}/data/{{item.dest}}"
    owner: solr
    group: solr
    mode: 0644
  with_items: "{{solr_config_j2_templates}}"

- service:
    name: solr
    state: restarted
