---
- include_role:
    name: geerlingguy.java
  tags:
    - solr

- include_role:
    name: geerlingguy.solr
  tags:
    - solr

- include: tasks/solr-standalone_tag.yml
  tags:
    - solr-standalone
