---
- include_role:
    name: geerlingguy.java
  tags:
    - solr-standalone
    - solr-cloud

- include_role:
    name: geerlingguy.solr
  tags:
    - solr-standalone
    - solr-cloud

- include: tasks/solr-standalone_tag.yml
  tags:
    - solr-standalone

- include: tasks/solr-cloud_tag.yml
  tags:
    - solr-zookeeper
    - solr-cloud

- include: tasks/active_solr_core.yml
  tags:
    - solr-active-core

# TODO mover esto a el rol de checkmk
- template:
    src: templates/check_mk_solr_plugin
    dest: /usr/share/check-mk-agent/plugins/solr
    owner: root
    group: root
    mode: 0755
  tags:
    - checkmk
