---
- name: Copy solr.xml config in cloud version
  template:
    src: "templates/solr_cloud.xml.j2"
    dest: "{{solr_home}}/data/solr.xml"
    owner: solr
    group: solr
    mode: 0644

- include_role:
    name: AnsibleShipyard.ansible-zookeeper

- name: Add cloud config in /etc/default/solr.in.sh
  lineinfile:
    dest: "/etc/default/solr.in.sh"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^ZK_HOST="
      line: 'ZK_HOST="localhost:2181"'
    - regexp: "^SOLR_HOST="
      line: 'SOLR_HOST="localhost"'
    - regexp: "^SOLR_OPTS="
      line: "SOLR_OPTS=\"{{solr_opts}}\""

- name: Configure Zookeeper
  template:
    src: templates/zoo.cfg.j2
    dest: "{{zookeeper_dir}}/conf/zoo.cfg"
    owner: zookeeper
    mode: 0644

- file:
    path: "{{solr_home}}/solr_cloud_mode.flag"
    owner: solr
    group: solr
    mode: 0644
